# Generated by Django 5.2.11 on 2026-03-10 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_pokemonentity_defense_pokemonentity_health_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='pokemonentity',
            name='id',
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pokemon_entities.pokemon'),
        ),
    ]
