# Generated by Django 5.2.11 on 2026-03-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0007_pokemon_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='name',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
