# Generated by Django 5.2.11 on 2026-03-13 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0011_remove_pokemon_evolved_from_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='title',
            new_name='title_ru',
        ),
    ]
