# Generated by Django 5.2.11 on 2026-03-13 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0017_alter_pokemonentity_appeared_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='disappeared',
            new_name='disappeared_at',
        ),
    ]
